fix(samples): isolate Spanner table name in spring-cloud-gcp-data-multi-sample (#4543)
Use unique Spanner table name `traders_multi_sample` instead of
`traders_repository` in `spring-cloud-gcp-data-multi-sample` to prevent
table schema collisions with
`spring-cloud-gcp-data-spanner-repository-sample`. Also guard DDL
execution in `MultipleDataModuleIntegrationTest.beforeAll` with
`tableExists` check.

Error:
```
Error: 0:897 [ERROR] com.example.MultipleDataModuleIntegrationTest -- Time elapsed: 13.68 s <<< ERROR!
com.google.cloud.spring.data.spanner.core.mapping.SpannerDataException: DDL could not be executed
	at com.google.cloud.spring.data.spanner.core.admin.SpannerDatabaseAdminTemplate.executeDdlStrings(SpannerDatabaseAdminTemplate.java:111)
	at com.example.MultipleDataModuleIntegrationTest.beforeAll(MultipleDataModuleIntegrationTest.java:60)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: Operation with name "projects/spring-cloud-gcp-ci/instances/spring-demo/databases/trades_25/operations/rc04a1660_adb0_4ec7_a039_cea98e34203d" failed with status = GrpcStatusCode***transportCode=FAILED_PRECONDITION*** and message = Duplicate name in schema: traders_repository.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:292)
	at com.google.common.util.concurrent.AbstractFutureState.blockingGet(AbstractFutureState.java:255)
	at com.google.common.util.concurrent.Platform.get(Platform.java:54)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:253)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
	at com.google.cloud.spring.data.spanner.core.admin.SpannerDatabaseAdminTemplate.executeDdlStrings(SpannerDatabaseAdminTemplate.java:105)
```