fix: noSuchMethodError in BigQuerySampleApplicationIntegrationTests (#3146)
needed to override spring dependency for OpenTelemtry api to ensure we have the latest OpenTelemtry dependency when using older versions of spring