Add class condition on ManagedChannel
This fixes the edge case where the project has the `spring.cloud.gcp.pubsub.emulator-host` set but not actually imports the `spring-cloud-gcp-starter-pubsub` starter.

Before this change, this would cause a `NoClassDefFoundError` when the auto config encountered the `GcpPubSubEmulatorAutoConfiguration`.